# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37475fce80c5ebb69690247519389be3d3bbabbe739860c014b024c9fc89a99c6285af30aa00f57f5e49ad8f90af8fe9752b613f5ff8b0e7ca338225bc098303

test:
  secret_key_base: 9b6d50246cd1c650133a1a51312742936562488abb8230f3243978aa8279dad829a9405982226767781c272fa5062a0011212ca9a1ff3610a2aa27910c052da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
